name: my-pipeline

on:
  push:
    branches: main
  pull_request:
    branches: [main, dev, prod]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      # Extract the current tag and set it as environment variable
      # - name: Extract tag
      #   run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF})"

      - name: Print Branch name
        run: |
            pwd
            echo $BRANCH_NAME
        env:
          BRANCH_NAME: "${{github.base_ref}}"

