name: my-pipeline

on:
  push:
    branches: main
  pull_request:
    branches: [main, dev, prod]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: If branch name is main
        if: ${{ github.base_ref == 'main' }}
        run: |
          echo 'main'
          echo ${{ github.base_ref }}
          echo '${{ github.base_ref }}'
          
      - name: If branch name is dev
        if: ${{ github.base_ref == 'dev' }}
        run: |
          echo 'dev'
          echo ${{ github.base_ref }}
          echo '${{ github.base_ref }}'

      - name: If branch name is prod
        if: ${{ github.base_ref == 'prod' }}
        run: |
          echo 'prod'
          echo ${{ github.base_ref }}
          echo '${{ github.base_ref }}'