name: my-pipeline

on:
  push:
    branches: main
  pull_request:
    branches: [main, dev, prod]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2
        with:
          # fetch-depth: 0
          # ref: ${{ github.ref }}
          persist-credentials: true

      - name: Print Branch Name
        run: |
          echo ${{ github.base_ref }}

      # This step stops the pipeline if the target branch is not main, dev, prod
      - name: Invalid tag
        if:  ! (${{ github.base_ref == 'main' }} ||  ${{ github.base_ref == 'prod' }} ||  ${{ github.base_ref == 'dev' }})
        run: |
          echo "The pipeline will get triggered only if pull request is made to one of these branches: 'sandpit', 'dev'"
          exit 1

      - name: If branch name is main
        if: ${{ github.base_ref == 'main' }}
        run: |
          echo "branch_name=${{ github.base_ref }}" >> "$GITHUB_ENV"
          echo "branch_secret=main-123" >> "$GITHUB_ENV"
          echo 'main'
          
      - name: If branch name is dev
        if: ${{ github.base_ref == 'dev' }}
        run: |
          echo "branch_name=${{ github.base_ref }}" >> "$GITHUB_ENV"
          echo "branch_secret=dec-123" >> "$GITHUB_ENV"
          echo 'dev'

      - name: If branch name is prod
        if: ${{ github.base_ref == 'prod' }}
        run: |
          echo "branch_name=${{ github.base_ref }}" >> "$GITHUB_ENV"
          echo "branch_secret=prod-123" >> "$GITHUB_ENV"
          echo 'prod'

      - name: Run the stuff
        run: |
          echo "${{ env.branch_name }}"
          echo "${{ env.branch_secret }}"

