# create a reusable workflow that has paython installed and can be used to run python scripts.
name: PL Dev Apply

on:
    workflow_call:
        inputs:
            env_name:
                description: 'Environment name'
                required: true
                default: 'Development'
                type: string

jobs:
    bulid:
        runs-on: ubuntu-latest
        environment: 
            # get the env name from the input
            name: ${{ inputs.env_name }}
            url: 'http://${{ inputs.env_name }}.example.com'
        
        # get environment variables from the environment
        env:
            ENV_NAME: ${{ vars.name }}
            ENV_URL: ${{ vars.url }}
            # get password from the environment
            ENV_PASSWORD: ${{ secrets.ENV_PASSWORD }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Run python script
              run: |
                  python --version
            
            - name: Print env variables
              run: |
                  echo $ENV_NAME
                  echo $ENV_URL
            
