# create a reusable workflow that has paython installed and can be used to run python scripts.
name: PL Dev Apply

on:
    workflow_call:
        inputs:
            config_path:
                description: 'Path to the config file'
                required: true
                type: string
                default: './config.yaml'

jobs:
    bulid:
        runs-on: ubuntu-latest
        environment: 
            name: Staging
            url: 'http://test.myapp.com'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requests==2.25.1
            - name: Run python script
              run: |
                  python --version
            # set up env name to dev
            - name: Set up env name
              run: |
                  echo "env_name: dev" >> ${{ github.workspace }}/${{ github.event.inputs.config_path }}
            
