# call reusable workflow on push and pull request events to main branch

name: Prodlib CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
    
          - name: Compile
            run: echo Hello, world!

    Sandpit-apply:
        if: github.event_name == 'pull_request'
        needs: [Build]
        uses: ./.github/workflows/prodlib_env_deployment.yaml
        with:
            env_name: 'Sandpitr'

    
    Dev-apply:
        if: github.event.ref == 'refs/heads/main'
        needs: [Build]
        uses: ./.github/workflows/prodlib_env_deployment.yaml
        with:
            env_name: 'Staging'
    
    Prod-apply:
        if: github.event.ref == 'refs/heads/main'
        needs: [ Dev-apply]
        uses: ./.github/workflows/prodlib_env_deployment.yaml
        with:
            env_name: 'Production'
        
