# This reusable workflow is used to deploy the product library to the specified environments
# The environment name is passed as an input to the workflow, the environment name is one of the following: 
#   - Standpit
#   - Development
#   - Production
# All the environment variables and secrets are stored in the corresponding environment and are retrieved from the environment

name: Product Library Deployment

on:
    # workflow is call inside another workflow
    workflow_call:
        inputs:
            env_name:
                description: 'Environment name'
                required: true
                default: 'Sandpit' # default value if not provided
                type: string

jobs:
    Terraform_Apply:
        runs-on: ubuntu-latest
        environment: 
            # get the env name from the input
            name: ${{ inputs.env_name }}
        
        # get environment variables from the environment
        env:
            ENV_NAME: ${{ vars.name }}
            ENV_PASSWORD: ${{ secrets.ENV_PASSWORD }}
        # run only if environment is only Sandpit, or Development or Production
        if: ${{ inputs.env_name == 'Sandpit' || inputs.env_name == 'Development' || inputs.env_name == 'Production' }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Run python script
              run: |
                  python --version
            
            - name: Print env variables
              run: |
                  echo $ENV_NAME
                  echo $ENV_PASSWORD
            
